### ISSUE TITLE
How to correctly apply filters to `getItems`

### ISSUE THREAD

**Issue by srajko** [jamesbirkett/node-axosoft#107]
Hi @jamesbirkett !

Thanks for this library, I've been using it for a project and it's been a huge help.

Just a quick question - can you please give an example of how to pass a filter to `getItems` (https://github.com/jamesbirkett/node-axosoft/blob/master/lib/items.js)? The docs say `filters` should be an object - I tried passing it in a few different ways but nothing I tried seems to have an effect.

**Comment by srajko** [comment]
Never mind, `getItems({ assigned_to_id: userId }, ...)` is working for me now.  I could have sworn I tried this before with no effect, I guess I was wrong :-)

**Comment by jamesbirkett** [comment]
Hi Stjepan,

Sorry for the slow reply, I've been on holiday.
Do these API docs help at all?
<http://developer.axosoft.com/api#!/items/_item_type_GET_get>

e.g. `var filters = {page: 1, pages: 2, customer_id: 456};`

James

James Birkett
Developer
www.footworksolutions.co.uk
Contact Number: 0845 8628811


DISCLAIMER......

This document is intended for, and should only be read by, those persons to
whom it is addressed. Its contents are confidential and if you have
received this message in error, please notify us immediately by telephone
and delete all records of the message from your computer. Any form of
reproduction, dissemination, copying, disclosure, modification,
distribution and / or publication of this message without our prior written
consent is strictly prohibited. Neither the author or their employers
accept legal responsibility for the contents of the message. Any views or
opinions presented are solely those of the author. Footwork Solutions Ltd.

**Comment by jamesbirkett** [comment]
Ah, I've just found this. I see you sorted it.
